### PR TITLE
Enhance PDF Report with Detailed Financial Summary and Dynamic Plot Inclusion #114

### PR DESCRIPTION
**Pull request by Ananya-vastare**
### Description
Please include a summary of the changes and the related issue. Also, explain the motivation behind this PR.
This PR enhances the visual aesthetics of the financial summary report by improving both the pie and line charts, as well as the PDF layout. The pie chart now features a modern Seaborn pastel color palette, shadow effects for a 3D appearance, and clearer wedge borders for better readability. The line chart has been updated with larger markers, smoother lines, and a refined grid to ensure clarity. Additionally, bolder titles and labels were applied to improve presentation. These enhancements are integrated into the PDF, which now includes the dynamically generated high-resolution plot, ensuring a professional, polished report. The motivation behind this PR is to address the original issue of basic, cluttered visuals, making the financial data easier to interpret and more appealing to present. These updates align with modern data visualization standards and significantly improve the user experience by delivering a clearer, more professional report output.

### Related Issue
Fixes # (issue)114

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [X ] I have commented on my code, particularly in hard-to-understand areas
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
- [X ] Any dependent changes have been merged and published in downstream modules
[John Doe-2024-10-11.pdf](https://github.com/user-attachments/files/17340145/John.Doe-2024-10-11.pdf)

### CODE REVIEW

**Comment by Ananya-vastare** [comment]
@multiverseweb any updates please??

**Comment by multiverseweb** [comment]
Hey @Ananya-vastare, sorry for the delay. In this PR, you have initialized the values to be plotted and used them to generate the report. Also, you have explicitly used the name `"John Doe"` for naming the pdf file. Here are the requirements that issue #114 and a much older similar issue #5 request:
- Create a pdf with the name `username-currentDate-Dataverse.pdf`.
- Take corresponding live data from mysql database.
- The report must contain the date, username, image of the line chart, pie chart, bar graph and the name `Dataverse` with logo.

**Review by multiverseweb — CHANGES_REQUESTED** [review]
Hey @Ananya-vastare, sorry for the delay. In this PR, you have initialized the values to be plotted and used them to generate the report. Also, you have explicitly used the name `"John Doe"` for naming the pdf file. Here are the requirements that issue #114 and a much older similar issue #5 request:
- Create a pdf with the name `username-currentDate-Dataverse.pdf`.
- Take corresponding live data from mysql database.
- The report must contain the date, username, image of the line chart, pie chart, bar graph and the name `Dataverse` with logo.

**Comment by Ananya-vastare** [comment]
@multiverseweb will make the necessary changes

**Comment by Ananya-vastare** [comment]
@multiverseweb I have made the desired changes please let me know if I have to change anything else thank you

**Comment by multiverseweb** [comment]
> @multiverseweb I have made the desired changes please let me know if I have to change anything else thank you

Hey @Ananya-vastare, I've been busy lately. Will check it out as soon as I get time.
Sorry for the inconvenience.

**Comment by Ananya-vastare** [comment]
@multiverseweb any updates please

**Comment by multiverseweb** [comment]
Yes, this looks fine. Thanks for your contribution @Ananya-vastare.
Ig you want to work on this further, create a new issue to integrate this `report generation feature` with the `software's GUI`.

**Pull request merged**
