### PR TITLE
Implemented Error Handling and Data Validation in Python Files #201

### LINKED ISSUE #201: Implement Error Handling and Data Validation in Python Files
###Description:
Enhance the robustness of the Python files in the project by implementing comprehensive error handling and data validation mechanisms. This will ensure the application can handle unexpected scenarios gracefully and provide meaningful feedback to the user.

###Tasks:
-Error Handling:
Implement try-except blocks around database connection and query execution code to handle database-related errors gracefully.
Provide user-friendly error messages using messagebox.showerror() to inform users about connection issues or query failures.
Ensure that all functions that interact with the database (e.g., view_data, check_credentials, fetch_data, etc.) include error handling.

-Data Validation:
Validate user input in the check_credentials function to ensure that the username and password fields are not empty before proceeding with the database query.
In the fetch_data function, check if the u_id provided is valid (e.g., a positive integer) before executing the query.
Ensure that any data processed from the database (e.g., dates, monetary values) are in the expected format. If not, return an appropriate error message.
Implement checks in the decrypt function to handle unexpected input lengths or formats.

-Unit Testing:
Write unit tests for the error handling and data validation logic to ensure that the implemented features work correctly.
Include test cases for both valid and invalid inputs to confirm that errors are handled appropriately.
Acceptance Criteria:
All database operations have robust error handling with user-friendly messages.
User input is validated before processing, and appropriate error messages are provided for invalid input.
Unit tests are implemented and successfully cover various scenarios.

### PR DESCRIPTION
**Pull request by Anushka-Pote**
### Description
Enhance the robustness of the Python files in the project by implementing comprehensive error handling and data validation mechanisms. This will ensure the application can handle unexpected scenarios gracefully and provide meaningful feedback to the user.

### Related Issue
Fixes #201 

### Type of change
- [X] Bug fix
- [X] New feature

### Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
@Anushka-Pote  Resolve all conflicts.

**Comment by Anushka-Pote** [comment]
Yeah, I got the conflicts, as there was another linear regression model merge made but, before making the PR I resolved all the the conflicts after sync on my local machine itself. You can see it as one of the 5 commits.
I don't think there should be any conflict left, but I will see it again

**Comment by Anushka-Pote** [comment]
I can see it's showing a conflict in one of the python files so yeah I will get on with it. But like after resolving it, I need to make a new PR or how should I proceed?

**Comment by jency1** [comment]
@multiverseweb

**Comment by Anushka-Pote** [comment]
Have I resolved the conflicts or any other change is expected?

**Comment by multiverseweb** [comment]
@Anushka-Pote I'm testing the PR, will get back to you soon.

**Comment by Anushka-Pote** [comment]
Heyy
Actually tomorrow is the last day for any PR merges to be allowed, so could you please tell me if there needs any changes here or is it fine??

**Comment by jency1** [comment]
> Heyy Actually tomorrow is the last day for any PR merges to be allowed, so could you please tell me if there needs any changes here or is it fine??

@Anushka-Pote  There are conflicts. So you need to resolve it.

**Comment by Anushka-Pote** [comment]
There were conflicts before i agree, but then I had resolved all 
I don't know why this is happening again.

**Review by multiverseweb — CHANGES_REQUESTED** [review]
Hey @Anushka-Pote, there are some problems in this PR:
- You have removed the variable `z` which counts the number of failed login attempts so the code is throwing an error in the terminal in that scenario
image

> Add an error message for `invalid login attempts`. Leave the variable `z` as it is, I'll later add a feature that disables `finance tracker` for some time after `2 invalid login attempts`

Screenshot 2024-11-10 080515

- The colors of pie chart are not same as those used in the line chart.
> image
>
> This can be solved by adding `colors=colors[1:len(columns) + 1]` attribute here
>image
>

Kindly solve the stated problems to get the PR merged.

> [!NOTE]
> I understand that I'm late in reviewing the code and its the last day of GSSoC, so I'll be merging the PR with `level3` whether you resolve the stated problems timely or not. Will fix them myself otherwise.
Good luck!

**Comment by Anushka-Pote** [comment]
Hey I just saw the message right now, And I don't think it will be done by 7 pm to be honest

**Comment by multiverseweb** [comment]
Hey @Anushka-Pote no problem, just let me know if you would still like to contribute to the project.

**Pull request closed without merging**
