### PR TITLE
Added Project Structure in README

### LINKED ISSUE #271: [Doc]: Adding a Project Structure Map
Adding a clear structure map in the documentation to guide contributors on where specific files and folders are located and what they contain.
**For example:**

Project Root
├── src/ &nbsp;&nbsp;&nbsp;&nbsp;              # Core application files
│ ├── components/ &nbsp;&nbsp;&nbsp;&nbsp;                         # Reusable UI components
│ ├── services/ &nbsp;&nbsp;&nbsp;&nbsp;                                # API calls and business logic
│ ├── utils/ &nbsp;&nbsp;&nbsp;&nbsp;                                     # Utility functions
│ └── index.js  &nbsp;&nbsp;&nbsp;&nbsp;                               # Main entry file
├── assets/ &nbsp;&nbsp;&nbsp;&nbsp;                                   # Images, icons, and other static assets
├── config/    &nbsp;&nbsp;&nbsp;&nbsp;                                 # Configuration files (e.g., env variables)
└── README.md   &nbsp;&nbsp;&nbsp;&nbsp;                          # Project overview and instructions

- This helps new contributors quickly understand the project layout and find files easily.

**Note:** please kindly assign this issue under gssoc-extd and hacktoberfest-accepted and level

### PR DESCRIPTION
**Pull request by siri-chandana-macha**
### Description
I have added the Project Structure to the README . This  guides contributors on where specific files and folders are located and what they contain.

### Related Issue
Fixes #271

**Note:** @multiverseweb please make sure to add all the necessary labels in #271

### CODE REVIEW

**Review by multiverseweb — CHANGES_REQUESTED** [review]
@siri-chandana-macha you have added the structure in Readme file, which makes it long unnecessarily, also does this structure update automatically as many files will be added, deleted or renamed in future.  Checkout the project structure in my [other project](https://github.com/multiverseweb/CodeIt?tab=readme-ov-file#-project-structure), that is what should be done here too. 

- Give  a link to the `project structure file in readme,md.
- the structure should update automatically.

Good luck fixing the stated issue. You can ask if you have any doubts.

**Comment by siri-chandana-macha** [comment]
No it does not auto update

**Comment by siri-chandana-macha** [comment]
I will add in a separate file

**Comment by siri-chandana-macha** [comment]
@multiverseweb Yeah its long. I have added the Project Structure in a seperate file.

**Pull request closed without merging**
