### PR TITLE
Fixes The License Section

### PR DESCRIPTION
**Pull request by rupeshv2121**
Fixes the Issues in License Section.
Issue Number : #101 

@jency1

### CODE REVIEW

**Comment by jency1** [comment]
> Fixes the Issues in License Section. Issue Number : #101
> 
> @jency1

@rupeshv2121 There is a bug in home page, while scrolling the content is not visible except landing page and footer, so fix it.

Also , the current license page is looking more professional , so you can add the hover effect in that only, no need to modify the styling of it.

So fix these issues, to get the PR merged.

**Comment by rupeshv2121** [comment]
Ok @jency1 assign me

**Comment by rupeshv2121** [comment]
@jency1 but the issue that assign me in that particular task is not this sonthat I raise another issue for that

**Comment by jency1** [comment]
@rupeshv2121 You can add the hover effect in the current license page and create the new PR to get it merged.

As the next need not to be changed.

**Comment by rupeshv2121** [comment]
I do that pls merge this @jency1

**Comment by rupeshv2121** [comment]
@jency1 mam pls reply me

**Comment by jency1** [comment]
> @jency1 mam pls reply me

You have changed the entire layout of the license page, which wasn't necessary. You can fix any other issues instead.

**Comment by rupeshv2121** [comment]
@jency1 mam you see now license page is looking pretty good then earlier

**Pull request closed without merging**
