### PR TITLE
Converted_Images_to_WebP_for_Better_Optimization

### PR DESCRIPTION
**Pull request by smog-root**
**Fixes** #182 

- Converted all relevant images from formats like PNG and JPEG to WebP for better optimization and performance.
- WebP offers better compression without significant quality loss, which helps in reducing file sizes and improves page load speed.

**Changes:**

- Replaced existing image formats (JPEG, PNG) with WebP versions.
- Updated image references in HTML files to reflect the new WebP file paths.
- Verified that images render correctly in browsers that support WebP.

**Testing:**

- Verified on multiple browsers (Chrome, Firefox, etc.) to ensure proper image rendering.
- Ensured fallback mechanisms are in place for browsers that do not support WebP (if needed).

_**Note**_:  Add gssoc-ext with level3, hacktoberfest-accepted labels!

@multiverseweb

### CODE REVIEW

**Review by multiverseweb — COMMENTED** [review]
Hey @smog-root, there are some issues with this PR:
- The website in this PR is taking like 10-12 seconds to load, while the current live website is taking less than 1 second on my internet connection. What do you think about this?
- Some images have issue with path:
image

**Comment by smog-root** [comment]
> Hey @smog-root, there are some issues with this PR:
> - The website in this PR is taking like 10-12 seconds to load, while the current live website is taking less than 1 second on my internet connection. What do you think about this?
> - Some images have issue with path:
> image
> 

@multiverseweb which Page is it?? File??

**Comment by multiverseweb** [comment]
@smog-root it's the landing page. `index.html`

**Comment by smog-root** [comment]
> @smog-root it's the landing page. `index.html`

I will resolve it!

**Comment by smog-root** [comment]
i have updated the index.html !

and there are no error now! @multiverseweb 

**Proof:** (screen recording)!

https://mega.nz/file/kG8VCDaD#m29KPpI3RjLfiYHXnvGQkpyzcLnvF0NlB5tl4-zwLbw

**Comment by multiverseweb** [comment]
Yes @smog-root, almost done. The images on the website load faster now but you have changed the images in **`software`** folder too. Those images are being used in the software, not in the website. This will create errors in the `python code`.

This won't be solved by adjusting the paths in python files as `tkinter` does not support `.webp` files. 
Hope you can insert `pngs` again. 
God Luck!

**Comment by smog-root** [comment]
> Yes @smog-root, almost done. The images on the website load faster now but you have changed the images in **`software`** folder too. Those images are being used in the software, not in the website. This will create errors in the `python code`.
> 
> This won't be solved by adjusting the paths in python files as `tkinter` does not support `.webp` files. Hope you can insert `pngs` again. God Luck!

okay i will convert to pngs again! 😞 . you should have said it first!

**Comment by multiverseweb** [comment]
Come on @smog-root, the folders have been given names for a reason. You should see which images are being used in the website.

**Comment by smog-root** [comment]
The following images are used in frontend:

settings.webp
top.webp
3d_glow.webp
about_down.webp
finance_down.webp
galaxy.webp
3d_glow.webp
wordcloud.webp
portal.webp
stars.webp
develop_up.webp
develop_down.webp
cubes.webp

i will convert back every image into png except this ⬆️ ! @multiverseweb

**Comment by multiverseweb** [comment]
@smog-root all the images being used in website are in this folder [/website/web_images](https://github.com/multiverseweb/Dataverse/tree/main/website/web_images).

**Comment by smog-root** [comment]
@i have converted them to png's! check it!! @multiverseweb

**Comment by smog-root** [comment]
@multiverseweb MERGE IT!!!

**Comment by smog-root** [comment]
@multiverseweb what happened? why are you not responding???

**Comment by multiverseweb** [comment]
Hey @smog-root, there are an issue in this PR:
- You have replaced `3d.gif` with `3d_glow.webp` in line number 207 in `index.html`.

> image
> This creates the following problem in examples section:
> Screenshot (110)

Hope you can fix this.

**Comment by smog-root** [comment]
@multiverseweb changd!!

**Pull request merged**
