### PR TITLE
Main

### PR DESCRIPTION
**Pull request by snehas-05**
Issue number #405
This PR introduces a 5-star rating and review system to the Dataverse platform, allowing users to provide feedback and rate the platform. The system is designed to engage the community, encourage quality feedback, and help potential users assess the platform's performance based on user ratings.

Key Features:
Rating System: Users can rate Dataverse from 1 to 5 stars using a user-friendly interface.

Review Submission: Alongside the rating, users can submit a detailed review describing their experience with the platform.

Real-Time Feedback Display: Submitted ratings and reviews are stored in a MySQL database and displayed immediately on the page, showing the average rating and the most recent reviews.

Data Storage: Reviews are stored in a MySQL database, including user information (name, email), the rating score, review text, and a timestamp.

Frontend: The user interface includes a responsive form for rating and review submission, as well as a section that displays the most recent reviews. The UI has been styled using custom CSS for a clean and consistent look.

### Type of change
- [ ] Bug fix
- [ ✔] New feature

### Checklist
- [✔ ] My code follows the style guidelines of this project
- [✔ ] I have performed a self-review of my own code
- [✔ ] I have commented on my code, particularly in hard-to-understand areas
- [✔ ] I have added tests that prove my fix is effective or that my feature works
- [✔ ] New and existing unit tests pass locally with my changes
- [✔ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
@snehas-05  Attach relevant screenshots.

**Comment by multiverseweb** [comment]
Hello @snehas-05, looks like you have created a separate page for the Star review system. Can you integrate it in the existing form:
image

as discussed in the issue #167?

Also, there is some problem with the `Submit Review` button, it triggers error in js:
image

Let me know if I'm doing it wrong. Hope you can fix the stated changes : )

**Comment by snehas-05** [comment]
Hey @Tejas-Gupta-7 I have made some changes and committed them. Can you have a look at them for once?

**Comment by multiverseweb** [comment]
Hey @snehas-05, a new form has been created in this PR which appears at the top of hop page.
image

I was expecting a new field like this being added to the existing form. The feedback is being stored on netlify. You just need to add some radio buttons as stars that will work as rating to the existing form:

image

**Comment by multiverseweb** [comment]
You can create a new PR when you solve the issue, I'm closing this one

**Pull request closed without merging**
