### PR TITLE
Fix input validation for Name and Message fields

### PR DESCRIPTION
**Pull request by Kunj05**
### Fix Input Validation Issue:   Name and Description Fields Ignored #2

This pull request addresses issue #2, where the Name and Description fields were not properly validated before form submission.

**Changes made:**
- Updated the `validateForm` function to ensure that both fields are checked and validated.
- Added user-friendly alerts to guide users when fields are left empty.

Looking forward to your feedback!

### CODE REVIEW

**Comment by multiverseweb** [comment]
Yes, now the input fields are compulsory, but since you changed the message field from `<input>` to `<textarea>`, the styling has changed. It'd be great if you could fix that too.

**Comment by Kunj05** [comment]
Ok i will fix that

**Comment by multiverseweb** [comment]
Yep, now it looks right. Merging.

**Comment by Kunj05** [comment]
Can u add the gssoc-ext
 and hacktoberfest label

**Comment by multiverseweb** [comment]
@Kunj05 done.

**Pull request merged**
