### PR TITLE
Contributions count not updating #303

### PR DESCRIPTION
**Pull request by Rohan20-10**
### Related Issue
Fixes # (https://github.com/multiverseweb/Dataverse/issues/303)

### Type of change
- [x] Bug fix
- [ ] New feature

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

@multiverseweb I have updated the total contributions count in the given code. Please review this pr and let me know if any changes are required. Thanks.

### CODE REVIEW

**Comment by amin-xiv** [comment]
For some reason it is not opening for me, the buffer just keeps spinning.

**Comment by Rohan20-10** [comment]
> For some reason it is not opening for me, the buffer just keeps spinning.

@amin-xiv yeah even I'm facing the same issue but when I executed, it was loading properly. Thanks for pointing it out.

**Comment by jency1** [comment]
> > > For some reason it is not opening for me, the buffer just keeps spinning.
> > 
> > 
> > @amin-xiv yeah even I'm facing the same issue but when I executed, it was loading properly. Thanks for pointing it out.
> 
> Still there is an issue of buffering, the page is only loading. So fix it, to get the PR merged.

**Comment by multiverseweb** [comment]
@Rohan20-10 @amin-xiv what shall we do? I'm not merging the PR for now as the loader keeps spinning. Another contributor is working on the same issue in my other project [CodeIt](https://github.com/multiverseweb/CodeIt). Let's see what he comes up with.

**Comment by Rohan20-10** [comment]
@multiverseweb @jency1 I have updated my code. Kindly review it once. Thanks.

**Comment by multiverseweb** [comment]
Hi @Rohan20-10, I don't know why the contributors stats are still not loading. Is it working on your side?

**Comment by amin-xiv** [comment]
@multiverseweb I have already fixed it last time, but I was told it was not going to be merged because another contributor was working on it, it woks on my local machine, and in the Netlify deploy preview, so can I submit it for PR again? Thank you.

**Comment by multiverseweb** [comment]
Sure @amin-xiv, create a new PR

**Comment by amin-xiv** [comment]
@multiverseweb #322

**Pull request closed without merging**
