### PR TITLE
Improved SignUp and Login Pages

### LINKED ISSUE #208: Enhancing Login/Signup Pages
The current pages have 0 to no styling. I would like to give them a minimalist look.

Screenshot 2024-10-21 145849
Screenshot 2024-10-21 145855

And also signUp form has no margin-bottom

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

### PR DESCRIPTION
**Pull request by Bhum-ika**
### Description
This PR has contributed in the improvement of UI and making those pages responsive

### Related Issue
Fixes #208 

### Type of change
- [ ] Bug fix
- [x] New feature

Screenshot 2024-10-24 125013
Screenshot 2024-10-24 125023
Screenshot 2024-10-24 125034
Screenshot 2024-10-24 125043

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
@Bhum-ika Something went wrong, do check it and fix it. The login / signup page is not working.

Screenshot 2024-10-24 194036

**Comment by Bhum-ika** [comment]
@jency1  kindly have a look on the issue. I only mentioned to improve UI, not functionality

**Comment by Bhum-ika** [comment]
@Tejas-Gupta-7 Please have a look

**Comment by multiverseweb** [comment]
Hey @Bhum-ika, the design of the page in this PR is very different as compared to that of the existing website as discussed in #208.
Also, the issue has been resolved here #237, so I'll be closing this PR. Let me know if you want to discuss this further.

**Pull request closed without merging**
