### PR TITLE
Fixed header styling

### PR DESCRIPTION
**Pull request by BhavaniSankar0107**
### Description
1. I have added a name after logo and made sure that it will disappear in mobile view
2. I have also added space between login/signup button and menu option

### Type of change
- [x] New feature
- [x] Enhancement

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jency1** [comment]
@BhavaniSankar0107 Mention the issue number which you have solved.

And resolve all conflicts.

**Comment by BhavaniSankar0107** [comment]
I have solved issue no. #195 , please review changes and assign necessary labels

**Comment by multiverseweb** [comment]
@BhavaniSankar0107 there is problem with the positioning of `Login/SignUp` button. It overflows to the right of the page in less wide screens.

**Comment by multiverseweb** [comment]
@BhavaniSankar0107 I'm closing this PR as the issue has not been resolved, here is the relevant screen recording:

https://github.com/user-attachments/assets/fdcb3a42-f4b0-48bd-9279-92a1b8a50d2c

**Pull request closed without merging**
