### PR TITLE
solved issue #98

### LINKED ISSUE #98: Login/signup page
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

There is not any login/signup option page.

### Proposed Solution

- creating a login/signup page

### Screenshot/Mockup (Optional)
Screenshot 2024-10-09 023405
Screenshot 2024-10-09 023358

### Alternatives Considered

- List any alternative solutions or features you’ve considered before suggesting this one.

### Additional Context

- Include any extra details, links, or documents that can help clarify or support your feature request.

### Requirement/Document

- Share any document that outlines or supports this feature request.

### PR DESCRIPTION
**Pull request by Devanshu1603**
### Description
Added a login/ Signup button.

### Related Issue
Fixes #98

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Devanshu1603** [comment]
@jency1  please review the PR and merge it accordingly.

**Comment by jency1** [comment]
> @jency1 please review the PR and merge it accordingly.

@Devanshu1603 On scrolling the home page the content is not visible, except the landing page and the footer. So fix that issue to get the PR merged. 

Also add the back to home button in login and signup page, as there is no option for it. OR you can add the same header, whatever is comfortable to you.

**Comment by Devanshu1603** [comment]
i couldn't get your point about scrolling on home page , can you provide screenshots,  as i only added the login/signup page.

**Comment by Devanshu1603** [comment]
@jency1  i have added back to home button on both login and signup page

**Comment by jency1** [comment]
> i couldn't get your point about scrolling on home page , can you provide screenshots, as i only added the login/signup page.

This issue is now solved! Now working properly

**Comment by jency1** [comment]
> @jency1 i have added back to home button on both login and signup page

Screenshot 2024-10-11 035815

Can you add this on left side with the content in single line ?

Everything else LGTM!

**Comment by Devanshu1603** [comment]
@jency1 ok i am do it right now . give me 2 min

**Comment by Devanshu1603** [comment]
> > @jency1 i have added back to home button on both login and signup page
> 
> Screenshot 2024-10-11 035815
> 
> Can you add this on left side with the content in single line ?
> 
> Everything else LGTM!

Done

**Pull request merged**
