### PR TITLE
Added github issue labeler workflow

### LINKED ISSUE #202: Implement Auto Labeling for Issues
# Title:  
Implement Auto Labeling for Issues

## Description:  
This feature aims to automate the process of assigning labels to issues when they are created or edited. The following labels will be automatically added:

- **gssoc-extd**: Marks the issue as part of GSSOC-extended contributions.  
- **hacktoberfest**: Marks it as eligible for Hacktoberfest.  
- **level?**: A placeholder label indicating the level, which will remain until the project admin assigns the appropriate level during the Pull Request (PR) review.

## Tasks:  
1. Create a **GitHub Action** that listens to issue events (`opened`, `edited`).  
2. Automatically assign the following labels:
   - `gssoc-extd`
   - `hacktoberfest`
   - `level?`  

3. Ensure the placeholder label `level?` remains on the issue until the project admin assigns the final level during the PR stage.  
4. Test the automation by creating and editing issues.

## Acceptance Criteria:  
- [ ] Labels are added to issues automatically upon creation or editing.  
- [ ] Placeholder label `level?` is correctly assigned to issues.  
- [ ] Final level is assigned by the project admin during PR review.  

@multiverseweb
Pls assign me this issue and give me level3,hacktoberfest-accepted and gssoc-extd

### PR DESCRIPTION
**Pull request by ygowthamr**
## Description:  
This PR adds a GitHub Action to automate labeling of issues on creation or edit.  
The labels added are `gssoc-extd` (green), `hacktoberfest` (orange), and `level?` (purple).  
`level?` serves as a placeholder until the project admin assigns the final level during PR review.  
The workflow uses the GitHub API to ensure labels are updated with correct colors and descriptions

Fix #202 

@multiverseweb 
Pls add labels like level3,gssoc-extd,hacktoberfest-accepted.

### CODE REVIEW

**Comment by ygowthamr** [comment]
@multiverseweb 
Pls check and merge my pr

**Comment by ygowthamr** [comment]
@multiverseweb 
Pls review and merge my also add labels to this pr

**Comment by ygowthamr** [comment]
@multiverseweb 
Pls review and merge my PR

**Comment by ygowthamr** [comment]
@multiverseweb 
Pls review and merge my PR

**Comment by ygowthamr** [comment]
@multiverseweb 
Pls review and merge my PR.

**Comment by ygowthamr** [comment]
@jency1 
You have assigned me wrong level it should be level3 as it is in issue

**Comment by ygowthamr** [comment]
@multiverseweb 
Pls merge this PR

**Comment by jency1** [comment]
> @multiverseweb Pls merge this PR

I have requested a review from the project admin. You don't need to comment again and again. 

He will merge whenever he will get free.

**Comment by multiverseweb** [comment]
@ygowthamr I'll check the PR tonight.

**Comment by ygowthamr** [comment]
@multiverseweb 
Thank you

**Review by multiverseweb — CHANGES_REQUESTED** [review]
Hey @ygowthamr, 
As stated under #202, we want **only one** label to be added automatically i.e. `Review Queued` of `#ffae00` color.
I hope you can make the required changes.

**Review by multiverseweb — APPROVED** [review]

**Comment by multiverseweb** [comment]
@ygowthamr I tested the workflow by raising a dummy issue #245, these are the errors I got:
image

image

Can you fix this? Let me know if I'm doing it wrong.

**Pull request merged**
