### PR TITLE
Support Plotting RadarChart - issue #3 

### PR DESCRIPTION
**Pull request by Rohan20-10**
@multiverseweb, I have implemented the radar chart plot and the GUI input support.
Please verify and let me know of any changes to be made further.

### CODE REVIEW

**Comment by Rohan20-10** [comment]
@multiverseweb sorry I forgot to add the respective labels can you tell me any way to add it, since I tried but could not figure it out?

**Review by multiverseweb — APPROVED** [review]
Great work @Rohan20-10! Merging.

**Comment by multiverseweb** [comment]
> @multiverseweb sorry I forgot to add the respective labels can you tell me any way to add it, since I tried but could not figure it out?

Yes, I'm adding the labels. Thanks for your valuable contribution! 😄

**Comment by Rohan20-10** [comment]
> > @multiverseweb sorry I forgot to add the respective labels can you tell me any way to add it, since I tried but could not figure it out?
> 
> Yes, I'm adding the labels. Thanks for your valuable contribution! 😄

Thanks @multiverseweb for giving me this opportunity to contribute.

**Pull request merged**
