### PR TITLE
have changed login to profile and error messeges too

### LINKED ISSUE #276: after successful login the login button changes to profile icon
Have an idea for a new feature? Please fill out the sections below. 😊
###current problem
login button doesnt go even after login
error boxes are not following the guidelines

### Proposed Solution
adding a profile page having our info and contribution and after successful login login button changes to profile icon
error boxes comes on not following password guidelines and email tag

### PR DESCRIPTION
**Pull request by vibhamishra09**
### have changed login button to profile button after successful login and error boxes arrives when not following email and password guidlines

Fixes #276

### Type of change
- [x] Bug fix
- [x] New feature

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
@vibhamishra09 If you can show some video, then it would be better. Also, resolve all conflicts.

**Comment by vibhamishra09** [comment]
have made some changes

https://github.com/user-attachments/assets/d0c53b05-eb18-46a3-aca2-8e73aa88562e

**Comment by jency1** [comment]
@vibhamishra09  Resolve conflicts.

**Comment by multiverseweb** [comment]
Hey @vibhamishra09, it work great! But here are some changes I would suggest:
- fix the path of images in login.html
> Current
> image
>
> Expected
> image

- Change the content of `profile` button to the profile image. You can use this image, it is already in the repo: [website/web_images/user.png](https://github.com/multiverseweb/Dataverse/blob/main/website/web_images/user.png)
> 
> image

- Change the contents of this page to `Currently under development`.
> 
> image

Thanks for the wonderful contribution, hope you can make the changes soon.

**Comment by multiverseweb** [comment]
@vibhamishra09 reminder to make the stated changes, its the last chance to make your contribution count for `GSSoC`!
Good luck.

**Pull request closed without merging**
