### PR TITLE
Fixing the send button issue in the form #67

### LINKED ISSUE #67: Fixing the send button issue in the form
image

Fixing the send button issue in the form to make it better for ui/ux. 

Assign this to me under gssoc 2024 ext and hacktoberfest. i will work on fixing it.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
### Description
I have fixed the form layout and send button and it is looking more good now as you can see in the image :- 

image

### Related Issue
Fixes #67 

### Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tarunkumar2005** [comment]
@multiverseweb Can you review and merge it soon its been so many days since it is open

**Comment by tarunkumar2005** [comment]
@jency1 Can you review this PR and ask the admin to merge it

**Review by multiverseweb — CHANGES_REQUESTED** [review]
Hey @tarunkumar2005, I apologize for the delay. The form looks fine in desktop view but there are many issues in the mobile view. 
image

I think you missed something in the css file.

**Comment by tarunkumar2005** [comment]
@multiverseweb Now check there was issue in the style.css file there one person didn't comented the part responsive properly and that was breaking the code and so the responsiveness was not there, it is fixed now you can check.

**Comment by tarunkumar2005** [comment]
@multiverseweb Can you check the PR now i have fixed the issues now.

**Comment by tarunkumar2005** [comment]
@multiverseweb @jency1 Can you check the PR and merge it its been open for too long (reminder)

**Comment by MastanSayyad** [comment]
@multiverseweb Review this PR if it has done the requested changes and @tarunkumar2005 resolve the conflicts

**Comment by multiverseweb** [comment]
Hey @tarunkumar2005, sorry for delay in code review, was totally packed up.
This is how the current form looks in mobile view:
image

And this is the form in your PR:
image

Here are the issues with this PR:
- The font-style of the place holder in `message field` is different as compare to the other two fields.
- The font color of `Let Me Know Your Thoughts` has been changed, which makes it disappear in light mode.
- The margin between fields has been increased, which makes the form look vertically elongated.

The issue #67 only required aligning the `send` button, which certainly has been solved in you PR, but newer issues have been introduced.
The button alignment has already been fixed in some PR, as you can see [here](https://multiverse-dataverse.netlify.app/). Therefore, I'm closing the issue.
Let me know if you have further doubts.

**Pull request closed without merging**
