### PR TITLE
home page navbar and signup/login back to home button update

### LINKED ISSUE #171: Overlapping and hidden navbar content
Found a bug? Please fill out the sections below. 👍

### Current Behaviour
1) In home page, the login/signup and menu icon is overlapping
2) In sign up and login page, back to home button is hidden

### Expected Behaviour
1) better spacing should be there in between login/signup and menu icon
2) in signup/login,back to home button should be fully visible

### Screenshot
Screenshot 2024-10-17 at 8 04 40 PM

Screenshot 2024-10-17 at 8 05 36 PM

### Proposed Solution
1) better spacing should be there in between login/signup and menu icon
2) in signup and login page, the back to home button should be aligned properly.

### PR DESCRIPTION
**Pull request by saumyayadav25**
### Description
Updated Navbar of home page, updated signup/login page back to home button.
also, in sign up page, there was not enough spacing at the end of the box.

### Related Issue
Fixes #171 

#### Before:
before version can be seen in the issue.
Screenshot 2024-10-19 at 4 21 56 PM

#### After:
Screenshot 2024-10-19 at 4 22 26 PM
Screenshot 2024-10-19 at 4 21 39 PM
Screenshot 2024-10-19 at 4 20 14 PM

### Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
@saumyayadav25  Yoh have just added padding , there is no change in the feature or something.

**Comment by saumyayadav25** [comment]
> @saumyayadav25 Yoh have just added padding , there is no change in the feature or something.

yes, in issue i mentioned that the signup/login and menu are overlapping and 

in signup and login page both, back to home page was hidden.

So, i was supposed to make those changes only according to the issue.

- if any other changes are required then do let me know

**Comment by multiverseweb** [comment]
Hey @saumyayadav25, you have hard-coded the position of the buttons according to the dimensions if your device's screen. This is how is looks on my computer:
image

This can be solved by making the position absolute rand giving margin from right side to `Login/Signup` button and from left side to `Back to Home` button.

Hope you can fix this soon.

**Review by multiverseweb — CHANGES_REQUESTED** [review]
Hey @saumyayadav25, you have hard-coded the position of the buttons according to the dimensions if your device's screen. This is how is looks on my computer:
image

This can be solved by making the position absolute rand giving margin from right side to `Login/Signup` button and from left side to `Back to Home` button.

Hope you can fix this soon.

**Comment by saumyayadav25** [comment]
> Hey @saumyayadav25, you have hard-coded the position of the buttons according to the dimensions if your device's screen. This is how is looks on my computer: image
> 
> This can be solved by making the position absolute rand giving margin from right side to `Login/Signup` button and from left side to `Back to Home` button.
> 
> Hope you can fix this soon.

sure, i will fix this issue asap.

**Pull request closed without merging**
