### PR TITLE
Issue report form

### LINKED ISSUE #350: [Website] Add 'Report a bug' form
Have an idea for a new feature? Please fill out the sections below. 😊

### Current Behaviour

Currently, the users can't report any bugs directly through the website.

### Proposed Solution

Add a simple form in which the users, can report a bug, describe it, and may attach any screenshots/videos and then once it is submitted, it can be sent directly to a support email, so I'm thinking about using `multiverse.letter@gmail.com` as a support email. Let me know what you think.

### Screenshot/Mockup (Optional)

N/A

### Alternatives Considered

Maybe providing a link directly to the issues section in this repository.

### Additional Context

N/A

### Requirement/Document

N/A

### PR DESCRIPTION
**Pull request by amin-xiv**
### Description
Added the issue report form. I would like to know if there are any improvements needed.

### Related Issue
Fixes #350 

### Type of change
- [ ] Bug fix
- [x] New feature

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by multiverseweb** [comment]
Hi @amin-xiv, the form works fine on desktop, but there some issues with font-size and alignment in mobile-view. Here's the screenshot:
image

> [!TIP]
>  I was thinking if we can shift the form to a new page and link in the navbar. This will help us add more related links and information later to that page. Like `Support` and `FAQs` section.

Let me know if you need any help doing this.
Thanks! 😊

**Comment by amin-xiv** [comment]
> Hi @amin-xiv, the form works fine on desktop, but there some issues with font-size and alignment in mobile-view. Here's the screenshot: image
> 
> Tip
> 
> I was thinking if we can shift the form to a new page and link in the navbar. This will help us add more related links and information later to that page. Like `Support` and `FAQs` section.
> 
> Let me know if you need any help doing this. Thanks! 😊

Hi @multiverseweb , I will try to fix the issues when in mobile view, and I will be making a new page, maybe call it `support`. I have a suggestion, since the sidebar contains a link to the main page, but we are already in the main page, we can replace it with the link to the `support` page instead. What do you think about this? Thank you.

**Comment by amin-xiv** [comment]
Hi @multiverseweb , I have a question, what is `L`, since I am getting lots of console errors saying that `L is not defined`.
Here is where it is first used:
`var map = L.map('map', {....}`
Thank you.

**Comment by multiverseweb** [comment]
> > Hi @amin-xiv, the form works fine on desktop, but there some issues with font-size and alignment in mobile-view. Here's the screenshot: image
> > 
> > Tip
> > 
> > I was thinking if we can shift the form to a new page and link in the navbar. This will help us add more related links and information later to that page. Like `Support` and `FAQs` section.
> > 
> > Let me know if you need any help doing this. Thanks! 😊
> 
> Hi @multiverseweb , I will try to fix the issues when in mobile view, and I will be making a new page, maybe call it `support`. I have a suggestion, since the sidebar contains a link to the main page, but we are already in the main page, we can replace it with the link to the `support` page instead. What do you think about this? Thank you.

Yes @amin-xiv, we can replace it with `support`.

**Comment by multiverseweb** [comment]
> Hi @multiverseweb , I have a question, what is `L`, since I am getting lots of console errors saying that `L is not defined`.
> Here is where it is first used:
> `var map = L.map('map', {....}`
> Thank you.

@amin-xiv `L` is the global namespace for `Leaflet`, a popular open-source JavaScript library for interactive maps.
I have included these two lines in the `index.html` file and according to chatGPT, these console errors should not occur if these lines have been included.

```html
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
```

I'll look into it tonight, thanks for pointing it out!

**Comment by amin-xiv** [comment]
@multiverseweb Thanks for the clarification.

**Comment by amin-xiv** [comment]
Hi @multiverseweb ,
I have created the `support.html` page, along some empty cards and sections for future features such as `FAQs` section. Also, I removed the link in the sidebar to the home page and replaced it with the support page.

Since I had to link the `script.js` file, there were LOTS of console errors about elements missing from the `support` page due to the functionality in the `script.js` file, I had to add some checks (which will work perfectly fine in the main page) that checks the availability of the elements that are being used to avoid unneeded error messages in the other pages that use `script.js` file, and their have been some other minor adjustments to make it is smooth as possible.

Thank you.

**Review by multiverseweb — APPROVED** [review]

**Pull request merged**
