### PR TITLE
Enhancement of Top Button | Issue #55

### LINKED ISSUE #55: Back-To-Top Button Visibility Issue in Website
Back-To-Top Button in the website work improperly and degrade the UI and UX.

https://github.com/user-attachments/assets/51dd5b50-a3ad-43bb-a647-c0e8ca5f75a8

@multiverseweb please assign this to me.

### PR DESCRIPTION
**Pull request by Shariq2003**
### Description
Fix #55 

https://github.com/user-attachments/assets/a2adecd4-a389-43db-ba52-23e9d64f385e

### Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
> ### Description
> Fix #55
> 
>  bandicam.2024-10-07.19-02-12-742.mp4 
> ### Type of change
> * [x]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> 
> ### Checklist
> * [x]  My code follows the style guidelines of this project
> * [x]  I have performed a self-review of my own code
> * [x]  I have commented on my code, particularly in hard-to-understand areas
> * [x]  I have added tests that prove my fix is effective or that my feature works
> * [x]  New and existing unit tests pass locally with my changes
> * [x]  Any dependent changes have been merged and published in downstream modules

@Shariq2003 While going down, from " Want to contribute to this Project? " section , back to top button is not there, Fix that issue.

**Comment by 121hemank** [comment]
i want to work in this issue

**Comment by jency1** [comment]
@Shariq2003 Are you currently working on this issue ?

**Review by multiverseweb — COMMENTED** [review]
Hey @Shariq2003, you have made several unnecessary changed in the files. The issue could be resolved by just removing this condition:
image

Thanks for your time, I'm closing the issue.

**Comment by multiverseweb** [comment]
The issue has been resolved.

**Pull request closed without merging**
