### PR TITLE
updated login.html and signup.html

### PR DESCRIPTION
**Pull request by JahnavikaGopalbvrith**
### Description
#266 
Email Validation
Improvement: Consider adding more specific error messages for invalid email formats.
Password Validation
Improvement: Implement actual checks to enforce these rules before allowing the login
Password Strength Meter
Whether the Password is Strong, Moderate or Weak.
Clear Input Fields on Successful Login
Improvement: Only clear fields if the login is successful, not before. Move the clearing code to after the redirection.
Security Features
Improvement: Consider implementing additional security features, such as rate limiting on login attempts and two-factor authentication for enhanced security.

### Related Issue
Fixes # (issue)

### Type of change
- [x] Bug fix
- [x] New feature

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
@JahnavikaGopalbvrith  There is an error of small white text box in both sign up and login page, do fix it. Also mention the issue number which you have been assigned.

Screenshot 2024-11-04 234823

**Comment by JahnavikaGopalbvrith** [comment]
@jency1 No, it is not an error. It is a password strength meter that displays whether a password is strong, moderate, or weak using a bar. When you enter a password, it will show this information.

**Comment by jency1** [comment]
@JahnavikaGopalbvrith So make like that, as anyone who sees can get idea about it. By looking at white box, it seems an error only. So do work on it. Also resolve all conflicts.

**Comment by JahnavikaGopalbvrith** [comment]
@jency1 Is this okay? Any changes Let me know.

**Comment by jency1** [comment]
@JahnavikaGopalbvrith In login page, Already have an account is not visible. And make the style of both page same in password strength meter.

**Comment by jency1** [comment]
@JahnavikaGopalbvrith  Make all changes and Resolve all conflicts to get the PR merged.

**Comment by AKSHITHA-CHILUKA** [comment]
please merge this pr 
Regards,
community manager
gssoc-ext

**Comment by multiverseweb** [comment]
@JahnavikaGopalbvrith the project mentor has already listed some issues in this PR. Kindly fix them too and we'll merge it. Here's the further clarification:
**Login page:**


**Sign Up page:**



The thickness of `password strength meter` is different in both pages, kindly make them equal.

Let me know if you want to discuss this further.
Appreciate your reminder @AKSHITHA-CHILUKA

**Comment by JahnavikaGopalbvrith** [comment]
"@multiverseweb, I will make the changes and create a pull request."

**Review by multiverseweb — APPROVED** [review]

**Comment by JahnavikaGopalbvrith** [comment]
@multiverseweb, please merge this pull request, as tomorrow is the final day for the gssoc-ext

**Comment by jency1** [comment]
> @multiverseweb, please merge this pull request, as tomorrow is the final day for the gssoc-ext

Resolve conflicts to get the PR merged.

**Comment by JahnavikaGopalbvrith** [comment]
Screenshot_20241109_100639_Chrome


As the resolve conflict button is not enabled I am unable to resolve the conflict I have asked core team about the same issue they told me that the PA or mentor can also resolve the conflict

**Comment by multiverseweb** [comment]
@JahnavikaGopalbvrith the same issue appears on my device. This can be solved by creating a new, cleaner PR. Close this one and create a new PR without any further changes and we will merge it 👍

**Pull request closed without merging**
