### PR TITLE
Change in singup and login page text and margin height , change in ma…

### PR DESCRIPTION
**Pull request by priyanshukumar-001**
…in page where the distance between logo and review box was far and change in text near review box.

### Related Issue
Fixes # (issue)

### Type of change
- [There was a spelling mistake] Bug fix
- And a change was in review section where the distance between the logo and review section was far in footer.
- Also little changes in Login and singup page.The height of one was a kinda short.

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by priyanshukumar-001** [comment]
Please review it i,m a begginer and was eager to contribute

**Comment by multiverseweb** [comment]
Hey @priyanshukumar-001, were you assigned to any issue?

**Comment by priyanshukumar-001** [comment]
> Hey @priyanshukumar-001, were you assigned to any issue?

No, but i wanted to try if i can make it better

**Comment by multiverseweb** [comment]
@priyanshukumar-001 You've made the form less wide:
image

I liked the wider one, specially in desktop view.
Raising an issue first is always better as it helps you save time and make useful efforts. Thanks for your idea thought.
Good luck!

**Pull request closed without merging**
