### PR TITLE
footer update

### PR DESCRIPTION
**Pull request by aashutosh585**
Hey @multiverseweb ,I have updated Footer of website, Take a look of it if you want some more change ,then let me know

**Before**

Screenshot 2024-10-22 233257

**After**

Screenshot 2024-10-23 005007

And don't forgot to add hackcobar-fest gssoc-ext level 2 or level3.

### CODE REVIEW

**Comment by jency1** [comment]
@aashutosh585 Mention the issue number which you have solved. 

Also if can add a horizontal line or something at top of all the links, like it is there on top of copyright section.

**Comment by aashutosh585** [comment]
hey @jency1 ,Take a look of modified footer .if you want something else then tell me.
Screenshot 2024-10-25 005215

And don't forgot to add hackcobar-fest gssoc-ext level 2 or level3.

**Comment by multiverseweb** [comment]
@aashutosh585, there are some problems with this PR:
- you added css code in `<style>` tag in html file even when `style.css` exists. It hinders code consistency and disturbs future contributors.
- The hover effect on links scales up their size, which moves the position of surrounding links a little. It didn't look good to me.

Can you just keep the style of the links as it is in the existing live site and remove the scale-up hover effect?
The main change I would like through this PR is moving the copyright section below the links.
Good luck!

**Comment by multiverseweb** [comment]
> @aashutosh585, there are some problems with this PR:
> 
> * you added css code in `<style>` tag in html file even when `style.css` exists. It hinders code consistency and disturbs future contributors.
> * The hover effect on links scales up their size, which moves the position of surrounding links a little. It didn't look good to me.
> 
> Can you just keep the style of the links as it is in the existing live site and remove the scale-up hover effect? The main change I would like through this PR is moving the copyright section below the links. Good luck!

@aashutosh585 
No commits have been made in this PR after I requested changes. Maybe you forgot to commit? Just check once
These are the animations effect I quoted in the earlier message:


https://github.com/user-attachments/assets/e2b0197f-1d0c-4cda-bac1-1121b63001ea

Hovering on one link, moves the contents around it. Can you remove this animation?

**Pull request closed without merging**
