### PR TITLE
Style updated for GET DIVERSE button

### LINKED ISSUE #247: UI enhancement : Enhance  GET DIVERSE Button Design on Homepage
Enhance the appearance and interactivity of the button on the homepage to improve user engagement and overall design consistency.

Video Screen1730005486649

@juikalage Can you assign this to me? I would love to work on this

### PR DESCRIPTION
**Pull request by swati-204**
### Description
I updated the button using CSS adding glow effect, changing border and inner text colors.
These changes make the button visually engaging and aligned with the project theme.

[Video Screen1730091757669.webm](https://github.com/user-attachments/assets/9efb84c3-180f-4262-96b8-eecd90061dca)

### Related Issue
Fixes #247 

### Type of change
- [ ] Bug fix
- [ ] New feature
- [x] UI Enhancement 

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
@swati-204 I am not able to see any hover effect and style changes on Get Dataverse button. Also in dark mode Get is not visible.

**Comment by swati-204** [comment]
> @swati-204 I am not able to see any hover effect and style changes on Get Dataverse button. Also in dark mode Get is not visible.

@jency1 I have updated the changes, please let me know if it's visible!

**Comment by jency1** [comment]
@swati-204  Still not able to see your hover effect changes. Below is the attached video for your reference.

You can see your changes in deploy preview.


https://github.com/user-attachments/assets/603930e1-cd61-432e-9d4f-96506845f0e9

**Comment by multiverseweb** [comment]
@swati-204 even I'm not able to see the hover-effect. Also, I like the design of existing button better:
image

It matches with other buttons on the site like this one:
image

As we want the design to be simple and contain less animations, etc. I'm closing this PR, you can reach out to me if you want to discuss this further.
Thanks for your time and efforts! Good luck.

**Pull request closed without merging**
