### PR TITLE
Integrate Heatmap Feature into Dataverse

### PR DESCRIPTION
**Pull request by Sneha22072005**
Integrated a new heatmap feature into the Dataverse project, enhancing the data visualization capabilities of the application. The following key changes have been made:

Added Heatmap Functionality: Introduced a heatmap feature that allows users to visualize data distribution and relationships more intuitively. This feature aims to provide insights into patterns and trends within the dataset.

Code Updates:

Implemented the necessary code to generate heatmaps using Plotly within the existing data visualization section of the application.
Ensured compatibility with the current GUI structure and improved user experience by integrating the heatmap functionality seamlessly.

@multiverseweb

### CODE REVIEW

**Comment by multiverseweb** [comment]
This is the output I'm getting: 

image

The equation plotting option should be integrated with the GUI.

**Comment by multiverseweb** [comment]
Hey @Sneha22072005, I appreciate your determination. 
When I ran your code, this window opened first:

Screenshot (107)

and when I close it, then this window comes up:

image

We want to add `Heat Map` feature in the latter window.

**Comment by Sneha22072005** [comment]
I am here to learn afterall. Though I am not able to access the second window directly due to some issues, that's why I am not able to provide a proper solution. Though I'll try again. Thank you for the opportunity!

**Comment by multiverseweb** [comment]
@Sneha22072005 I completely understand. The code is complex and requires minute changes as well. Happy Learning! 😄

**Comment by Sneha22072005** [comment]
ill hope it works now. Did the changes @multiverseweb

**Comment by jency1** [comment]
> ill hope it works now. Did the changes @multiverseweb

@Sneha22072005 Resolve all conflicts.

**Comment by Sneha22072005** [comment]
@jency1 someone added a new function so that was just causing the issue now. I resolved the conflict

**Comment by Sneha22072005** [comment]
@multiverseweb  ?

**Review by multiverseweb — CHANGES_REQUESTED** [review]
Hey @Sneha22072005, 
I found the following problems in the code:

image

and

image


Looks like there is some problem with the `get_y_values()` function. I would be helpful if you could attach the screenshot of the output this code generates on your computer.

**Comment by multiverseweb** [comment]
Issue resolved #94

**Pull request closed without merging**
