### PR TITLE
Final commit (V2).

### PR DESCRIPTION
**Pull request by amin-xiv**
### Description
Hi @jency1 , there has been small light issues in the code, in which I have been willing to commit moments  before you merged the last PR, so here they are. Thank you.

### Related Issue
Fixes # (issue)

### Type of change
- [x] Bug fix
- [x] New feature

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
@amin-xiv Ok. Merging the PR but I am not assigning the level label as I have assigned in the previous PR only.

**Comment by amin-xiv** [comment]
@jency1 sorry, but I have always wondered, what does those level labels do? Thank you.

**Comment by multiverseweb** [comment]
@amin-xiv actually this project is a part of GirlScript Summer of Code Extended (GSSoC) 2024, which is a 1 month long competition that aims at promoting the Open Source community.

These level labels represent the number of points the contributor will get for everyone merged PR.
Level1 - 10 points 
Level2 - 25 points 
Level3 - 45 points

The winners are decided on the basis of the points they've earned and they get a lot of prizes. 

The competition is ending on 10th November, 2024.

You can get more information [here](https://gssoc.girlscript.tech/).

**Comment by amin-xiv** [comment]
@multiverseweb Thanks for the clarification 👍But basically it is safe to say that I have came late 😅

**Comment by multiverseweb** [comment]
> @multiverseweb Thanks for the clarification 👍But basically it is safe to say that I have came late 😅

Hey, no worries about the timing! You can still register as a contributor and earn some digital achievements if you wish 😄

**Comment by multiverseweb** [comment]
> @multiverseweb I have checked it out, but I have found out that it requires a LinkedIn profile, college/office name, but I am still in grade 9, so no registration for me ☺

@amin-xiv that's really impressive! You're already exploring these things at such a young age, that's awesome. Keep learning and building. 

Good luck

**Comment by amin-xiv** [comment]
Thanks a lot @multiverseweb , I really appreciate it.

**Pull request merged**
