### PR TITLE
now different tabs open

### PR DESCRIPTION
**Pull request by GauriSachan**
#8

### CODE REVIEW

**Comment by multiverseweb** [comment]
Hey @GauriSachan, this doesn't seem right. Looks like you just added `<a href="https://github.com/multiverseweb/Dataverse" target="_blank" class="table_link">GitHub Repository</a>` at the end of html file. I think this issue can be resolved by adding `target="_blank"` to all the links in the website.

**Comment by GauriSachan** [comment]
@multiverseweb done

**Comment by multiverseweb** [comment]
@GauriSachan Great, merged.

**Comment by GauriSachan** [comment]
@multiverseweb hey can you give the labels of level1,hactoberfest accepted and gssoc -ext in this pr as well? the issue was #8

**Comment by GauriSachan** [comment]
> @GauriSachan Great, merged.

hey can you please reopen the pr and add the labels and then close it? thank you

**Comment by multiverseweb** [comment]
Hey @GauriSachan, sorry for the inconvenience. I reverted the previous PR. Can you create a new PR so I'll assign labels and merge it?

**Pull request merged**
