### PR TITLE
Added the ability to toggle between view/hide password in the signup …

### LINKED ISSUE #144: View password feature in login page and signup page
**_I noticed that the sign-up form currently lacks a "view password" option, which could lead to user errors. I would like to take on the task of implementing this feature to enhance user experience. Please let me know if I can proceed with this improvement._**

Screenshot 2024-10-15 121013

Screenshot 2024-10-15 121102

I am confident that resolving these issues will improve the page's usability and overall aesthetic. Please let me know if I can take on this task and contribute to improving the website.

### PR DESCRIPTION
**Pull request by amin-xiv**
### Description
Now the user can view/hide their password in both the signup and login page.

### Related Issue
Fixes #144 

### Type of change
- [ ] Bug fix
- [x] New feature

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

toggle_password_visiblity

### CODE REVIEW

**Comment by jency1** [comment]
@amin-xiv Fix the alignment of toggle button, currently it's on the box.

**Comment by multiverseweb** [comment]
Hi @amin-xiv here are the two changes required:
- Avoid overlapping of eye image with text (can be done by adding background to the image)

Screenshot_2024-11-07-03-33-52-49_40deb401b9ffe8e1df2f1cc5ba480b12

- Switch the images upon toggle. 

eye-icons-set-password-eye-vision-illustration-sign-collection-suitable-for-design-element-of-user-login-ui-ux-free-vector

**Comment by amin-xiv** [comment]
@multiverseweb Alright thanks for the clarification 👌

**Comment by amin-xiv** [comment]
Hi @multiverseweb , I have updated it, what do you think now?

**Pull request merged**
