### PR TITLE
successfully redesigned login and signup pages according to website's theme

### PR DESCRIPTION
**Pull request by MimanshaKaur**
### Description
as earlier issue was:
- Login and sign up pages do not have properly centered aligned form.
- Login and sign up page have no background.
- NO proper title names for both the pages.

therefore,  to resolve this, i have : 
- i have redesigned everything on login and sign up page...
- it is completely made according to theme
- as page's load time was increased so i compressed the bg images and then used it
- added logo and your website's name  and  set the back to home button . 
- set all the form alignment.
- added proper title names for both the pages.

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by MimanshaKaur** [comment]
@multiverseweb done👍👍

**Comment by jency1** [comment]
@MimanshaKaur  Mention the issue number which you have solved and resolve all conflicts.

**Comment by multiverseweb** [comment]
Hello @MimanshaKaur, I couldn't see the same background in this PR as you showed [here](https://github.com/multiverseweb/Dataverse/issues/164#issuecomment-2430124138). Did you remove that on-purpose?

That was looking awesome, can you add it?

**Comment by MimanshaKaur** [comment]
> @MimanshaKaur Mention the issue number which you have solved and resolve all conflicts.
That was issue #164

**Comment by MimanshaKaur** [comment]
> Hello @MimanshaKaur, I couldn't see the same background in this PR as you showed [here](https://github.com/multiverseweb/Dataverse/issues/164#issuecomment-2430124138). Did you remove that on-purpose?
> 
> That was looking awesome, can you add it?

no i didn't removed it ...now check i have made some changes

**Comment by jency1** [comment]
@MimanshaKaur Resolve all conflicts.

**Comment by multiverseweb** [comment]
@MimanshaKaur I'm having trouble merging this PR, I tried merging it and then fixing the minute problems myself but its not allowing me to merge:
image

I found out why the images are not visible here:
Screenshot 2024-10-28 072125

You have used the local paths of images instead of relative paths. Solve it by using `website/web_images/2dglow.png` instead of `C:/Users/Mimansha/OneDrive/Documents/GitHub/Dataverse/website/web_images/2dglow.png`. Do the same for the other image.

**Comment by MimanshaKaur** [comment]
ok @multiverseweb

**Comment by MimanshaKaur** [comment]
@multiverseweb now see.. done with changes...i have now used the relative path address for both the pages

**Comment by jency1** [comment]
> @multiverseweb now see.. done with changes...i have now used the relative path address for both the pages

@MimanshaKaur LGTM! Resolve all conflicts to get the PR merged.

**Comment by multiverseweb** [comment]
@MimanshaKaur yeah go ahead, create a new PR.

**Comment by jency1** [comment]
@MimanshaKaur You must pull all the changes, then push your changes. So that if any conflicting lines of code are there, you can see it and resolve it.

**Comment by MimanshaKaur** [comment]
gonna create new PR👍

**Comment by MimanshaKaur** [comment]
#265 ..created new PR for this,,please check

**Pull request closed without merging**
