### PR TITLE
Done some enhancements and also added some new sections

### PR DESCRIPTION
**Pull request by milansamuel609**
### Description

I have done some enhancements and also added some new sections.

These are the changes I have done :-

1) Enhanced the project structure
2) Added project structure section
3) Added first pull request section
4) Added additional method of contributing through GitHub desktop section
5) Added good coding practices section
6) Added the help and support section
7) Added the pull request section
8) Added issue report process section

### Related Issue
Fixes: [#165 ]

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by milansamuel609** [comment]
I have enhanced the document. Please kindly check it once.

**Comment by jency1** [comment]
> I have enhanced the document. Please kindly check it once.

@milansamuel609  Provide relevant screenshots and write which document you have changes.

**Comment by milansamuel609** [comment]
> > I have enhanced the document. Please kindly check it once.
> 
> @milansamuel609 Provide relevant screenshots and write which document you have changes.

Sure I will do it right now 👍

**Comment by milansamuel609** [comment]
I have enhanced the Contributing.md file.
These are the screenshots of the enhancements I have done :-

image

image

image

image

image

**Comment by milansamuel609** [comment]
I have added the screenshots. Please check them once.

**Comment by milansamuel609** [comment]
Please check the changes once. If they are ok please kindly merge the PR.

**Comment by milansamuel609** [comment]
Please kindly merge my PR if all the changes done are fine and also please attach the labels for gssoc ext and level.

**Comment by jency1** [comment]
> Please kindly merge my PR if all the changes done are fine and also please attach the labels for gssoc ext and level.

@milansamuel609 Can you add " What you can contribute? " section and " Contribution Points " section ?

Screenshot 2024-10-22 174203

Screenshot 2024-10-22 174151

**Comment by milansamuel609** [comment]
> > Please kindly merge my PR if all the changes done are fine and also please attach the labels for gssoc ext and level.
> 
> @milansamuel609 Can you add " What you can contribute? " section and " Contribution Points " section ?
> 
> Screenshot 2024-10-22 174203
> 
> Screenshot 2024-10-22 174151

Sure I will do it right now 👍

**Comment by milansamuel609** [comment]
Please check it once. The sections you have asked for was already there I just aligned them as you have shown in the screenshots.

**Comment by milansamuel609** [comment]
Please kindly check the enhancements. If the enhancements are fine please kindly merge the PR.

**Comment by milansamuel609** [comment]
Please kindly merge the PR if all the changes are fine

**Comment by milansamuel609** [comment]
Please kindly check the changes once. If everything is fine please kindly merge the PR and also please add the gssoc and level label.

**Comment by milansamuel609** [comment]
Please check it once if everything is fine then please kindly merge the PR.

**Comment by multiverseweb** [comment]
Hey @milansamuel609, the file looks fine now but there is a mistake under `First Pull Request` heading:
image

There is not file named `Project-Guidance` in our repository.

**Comment by milansamuel609** [comment]
> Hey @milansamuel609, the file looks fine now but there is a mistake under `First Pull Request` heading: image
> 
> There is not file named `Project-Guidance` in our repository.

Sure I will fix it. Sorry for the mistake

**Comment by milansamuel609** [comment]
I have checked once again if any issue is there. Now the issue is fixed. Please check once

**Comment by milansamuel609** [comment]
If the changes are fine now please kindly merge the PR.

**Review by multiverseweb — APPROVED** [review]

**Pull request merged**
