### PR TITLE
Enhanced Login and Signup Pages

### PR DESCRIPTION
**Pull request by sagar27sahu**
### Description
improved the UI of the login and signup pages with a modern gradient background and frosted glass effect. Adjusted input fields, labels, and buttons for better alignment and readability. Added gradient hover effects for the primary buttons to improve user interaction. Updated layout to ensure responsive centering of the forms for a better user experience across different devices. Improved text styling for better accessibility and a clean, professional look.

i am attaching ss of my work-
Screenshot 2024-10-19 at 5 18 08 PM
Screenshot 2024-10-19 at 5 18 13 PM

### Related Issue
Fixes Issue #177

### Type of change
New feature (non-breaking change which adds functionality)

### Checklist
My code follows the style guidelines of this project
I have performed a self-review of my own code
 I have added tests that prove my fix is effective or that my feature works
 New and existing unit tests pass locally with my changes
 Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jency1** [comment]
@sagar27sahu Resolve all conflicts.

Also the text is not properly visible with this color. You must add the color relevant and matches the color of the website. And back to home button is also disappeared..

Fix all these issues to get the PR merged.

**Comment by jency1** [comment]
@sagar27sahu Solve all conflicts.

**Comment by jency1** [comment]
Back to top must be on header only, not in the login card.

**Comment by multiverseweb** [comment]
@sagar27sahu the aesthetics of the existing website possess a base color like `#ffffff` or `#000000` and the foreground contains multi-colored elements. Please style the `login / signup` page accordingly.

**Review by multiverseweb — CHANGES_REQUESTED** [review]
@sagar27sahu the aesthetics of the existing website possess a base color like `#ffffff` or `#000000` and the foreground contains multi-colored elements. Please style the `login / signup` page accordingly.

**Comment by multiverseweb** [comment]
@sagar27sahu The login and signup pages have been fixed in #237, so I'm closing this PR. Reach out to me if you have any doubts.

**Pull request closed without merging**
