### PR TITLE
header enhancement index.html

### PR DESCRIPTION
**Pull request by tejasam571**
### Description

This pull request introduces significant enhancements to the header section of the Dataverse web application, aimed at improving both usability and aesthetics. The header is designed using Flexbox, providing a responsive and structured layout that allows for better alignment of elements. The logo is accompanied by two versions—one static and one glowing—to enhance visual appeal and brand recognition. The navigation menu has been centered, ensuring easy access to important links, which are now styled to offer hover effects, enhancing user interactivity and engagement. External stylesheets have been included for Leaflet and Font Awesome, adding functionality and graphical icons that enrich the user experience. The overall code structure is clean and organized, utilizing semantic HTML elements that improve accessibility. Additionally, the use of a placeholder `<main>` section indicates where future content will be integrated, maintaining a clear separation between the header and the main body of the webpage. These improvements significantly elevate the project's quality, making it more attractive and easier for users to navigate. Forking the project head in GitHub is recommended to integrate these positive updates seamlessly into the existing framework.

### Related Issue
Fixes # (issue)

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

before it looked : 
Screenshot 2024-10-07 202814

now after the changes  :
Screenshot 2024-10-08 092723

### CODE REVIEW

**Comment by tejasam571** [comment]
i am both contributing in hacktober fest and gssoc! please do consider .

**Comment by tejasam571** [comment]
CONTIBUTION of the project "DATAVERSE " on the issue raised is completed !

**Comment by MastanSayyad** [comment]
@tejasam571 you don't need to tag everyone on your PR just tag the project admin @multiverseweb and it's mentors.

**Comment by jency1** [comment]
@tejasam571 The option for changing to light mode and dark mode is not there. Hovering  Effect can also be improved. 

Also in light mode, the text is not visible. So fix all issues to get the PR merged.

Screenshot 2024-10-08 162920

**Comment by tejasam571** [comment]
Sure , I'll send this by today! 🙂

**Pull request closed without merging**
