### PR TITLE
Add images to button issue #51

### PR DESCRIPTION
**Pull request by Rohan20-10**
### Description
Please include a summary of the changes and the related issue. Also, explain the motivation behind this PR.

### Related Issue
Fixes # ([issue](https://github.com/multiverseweb/Dataverse/issues/51))

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

@multiverseweb I have added the images for the buttons up to radar chart.
The remaining images are not available easily and do not characterize the particular plot clearly so if any changes required for those do let me know.
Attaching the screenshot of what I have attempted. Please review the pr.
Screenshot from 2024-10-13 11-27-04

### CODE REVIEW

**Review by multiverseweb — CHANGES_REQUESTED** [review]
Hey @Rohan20-10, I have two doubts regarding this PR.
- Is it possible to align the images to left withing the buttons?
- Can you keep the background of the images transparent as shown in the picture below:
image

**Comment by Rohan20-10** [comment]
@multiverseweb I can align that images to the left of the button.
The second point you mentioned about the transparent images is being implemented but the thing is that if I do the other way which you are suggesting then the problem is that when we hover over that button then that image hides. So I did this way. Pls let me know your feedback about it.

**Comment by Rohan20-10** [comment]
@multiverseweb any updates ?

**Comment by multiverseweb** [comment]
> @multiverseweb I can align that images to the left of the button. The second point you mentioned about the transparent images is being implemented but the thing is that if I do the other way which you are suggesting then the problem is that when we hover over that button then that image hides. So I did this way. Pls, let me know your feedback about it. To help you understand what I am saying, I've attached the video for the line graph image, which shows the changes you suggested. [Screen-Recording.webm](https://github.com/user-attachments/assets/aef0c6b7-8c37-4741-b4f5-870ec89c6ffc)

@Rohan20-10 sorry for the delay in reviewing the code, was overloaded with tasks.
Somehow this effect on `hover` does not appear on my computer. 
The better solution is to keep the images transparent, and we will create a new issue for `changing the button color on hover`. 
This will keep the images visible on hover too,.
What do you think?

**Review by multiverseweb — COMMENTED** [review]
Hey @Rohan20-10, kindly make the required changes and send the PR.

**Comment by Rohan20-10** [comment]
> Hey @Rohan20-10, kindly make the required changes and send the PR. Waiting to hear your opinion.

@multiverseweb Yeah, Sure. I will do what you suggested and then create a separate issue for the change in the visibility of images on hover. Thanks.

**Comment by Rohan20-10** [comment]
@multiverseweb I have made the changes that you suggested. 
Please review the pr. Thanks.

**Review by multiverseweb — APPROVED** [review]

**Comment by multiverseweb** [comment]
Looks great, merging.

**Comment by multiverseweb** [comment]
@Rohan20-10 checkout the latest version of the software, I've added images to all the buttons and fixed their dimensions

image

**Comment by Rohan20-10** [comment]
> @Rohan20-10 checkout the latest version of the software, I've added images to all the buttons and fixed their dimensions
> 
> image
It is looking fabulous. Great work @multiverseweb. Thanks.

**Pull request merged**
