### PR TITLE
Support Plotting 3D Scatter Plot

### PR DESCRIPTION
**Pull request by Rohan20-10**
@multiverseweb Done with implementing the 3d scatter plot for the data along with the GUI support for input.
Please review the pr.
Few things that I would like to tell you
1. Currently the data can be taken to plot only 16 points (let me know if that needs to be updated)
2. The color scheme used in the software cant be implemented here as the camp(color map) used here is standard "viridis"
3. The size of the points I have kept it as 60 by default. Do you want it based on the values of either x, y or z because then we have to take into consideration the value limit as well (let me know if that needs to be updated)
4. The legend will consist of what please clarify on that (let me know if that needs to be updated)
5. Also the opacity of these points currently is 50% opaque. (let me know if that needs to be updated)

**Final Implementation -**
3D_Scatter_plot

### CODE REVIEW

**Comment by Rohan20-10** [comment]
@multiverseweb Yeah even this time I couldn't find the option to add labels to my pull request. 
So, I humbly request that you add the labels.

**Comment by multiverseweb** [comment]
@Rohan20-10 sure, only project admin or mentors can add the labels.

**Comment by multiverseweb** [comment]
> @multiverseweb Done with implementing the 3d scatter plot for the data along with the GUI support for input. Please review the pr. Few things that I would like to tell you
> 
> 1. Currently the data can be taken to plot only 16 points (let me know if that needs to be updated)
> 2. The color scheme used in the software cant be implemented here as the camp(color map) used here is standard "viridis"
> 3. The size of the points I have kept it as 60 by default. Do you want it based on the values of either x, y or z because then we have to take into consideration the value limit as well (let me know if that needs to be updated)
> 4. The legend will consist of what please clarify on that (let me know if that needs to be updated)
> 5. Also the opacity of these points currently is 50% opaque. (let me know if that needs to be updated)
> 
> **Final Implementation -** 3D_Scatter_plot

Wait, checking.

**Comment by multiverseweb** [comment]
Hey @Rohan20-10, the GUI looks great But i faced two issues:
- The radar chart is not working in this PR, but is working in the current version on my repo.
- In some cases, the `plot` button triggers type error:
Screenshot 2024-10-06 003528

Again, thanks for your determination.

**Pull request closed without merging**
