### PR TITLE
Added a trailing cursor effect for enhanced user interaction

### PR DESCRIPTION
**Pull request by akhulisumit**
This pull request introduces a trailing cursor effect to improve user interaction and create a more dynamic interface. The effect follows the user's mouse movement, providing a visually engaging experience that complements the overall design.

https://github.com/user-attachments/assets/126d294c-25db-4d84-b46e-38e2ecb6d9da

### CODE REVIEW

**Comment by multiverseweb** [comment]
Hello @akhulisumit, you must wait for issue assignment before working it, this will help you getting more PRs merged and waste less time.

**Comment by akhulisumit** [comment]
I am extremely sorry for this. Can I please on this again.

**Comment by akhulisumit** [comment]
BTW your repo is good and I would like to make more contributions

**Comment by multiverseweb** [comment]
Thank you @akhulisumit, looking forward to valuable contributions from your side 😄

**Pull request closed without merging**
