### PR TITLE
Add Email Existence Check Before Form Submission 

### PR DESCRIPTION
**Pull request by HarshAgrawal1**
This PR introduces email validation functionality to the contact form by integrating the Abstract API. The primary goal is to ensure that users submit valid and deliverable email addresses, enhancing the reliability of user communications.

**Changes Implemented**

**Email Validation Function:** Developed an asynchronous function, validateEmailWithAPI, that utilizes the Abstract API to verify the validity and deliverability of email addresses. The function returns true for valid and deliverable emails, and false otherwise.
**Form Validation Workflow:** Updated the validateForm function to incorporate the email validation check. If the email is invalid or undeliverable, the form submission is halted, and an alert prompts the user to enter a valid email address.
**User Feedback:** Implemented alert messages to inform users of invalid email entries, ensuring a user-friendly experience.
Testing and Error Handling
**API Response Handling:** The validateEmailWithAPI function includes error handling to manage scenarios such as API request failures, which may occur if the free tier usage is exhausted. In such cases, the function logs an error message and returns true to ignore API call

### CODE REVIEW

**Comment by multiverseweb** [comment]
@HarshAgrawal1 I'm getting this screen on submitting the form:
image
Irrespective of the email's validity. Please correct me if I'm doing it wrong.

**Comment by HarshAgrawal1** [comment]
@multiverseweb when you're getting this screen? After submitting form?

**Comment by HarshAgrawal1** [comment]
Let me check too .

**Comment by HarshAgrawal1** [comment]
@multiverseweb   project is hosted on Netlify, as the form won’t work locally with **data-netlify="true"**. The Netlify form handling will only work once the website is deployed to Netlify’s servers.

**Pull request closed without merging**
