### PR TITLE
Added Typing effect in the Main Headings Only

### LINKED ISSUE #113: Title Description CSS Animation
The description under each sub topic is static.

@multiverseweb 

I want to induce a css styling for these texts like this--

https://github.com/user-attachments/assets/6f23bbe9-0cec-42b8-9250-0c0258bf69ff

This looks more creative and fun to read too.

### PR DESCRIPTION
**Pull request by ThunderShadows**
Description

The text styling of the website looked more static and for a professional website such as DataVerse interesting animations for the styling of the text headings where added to enhance readability. 

Related Issue
Fixes #113

Type of change

- [Y] New feature (non-breaking change which adds functionality)

Checklist
- [Y] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my own code
- [Y] I have commented on my code, particularly in hard-to-understand areas
- [Y] I have added tests that prove my fix is effective or that my feature works
- [Y] New and existing unit tests pass locally with my changes
- [Y] Any dependent changes have been merged and published in downstream modules

Additional Queries-

I shall include the animations to the description under each sub headings if you like this one. I shall create a new issue and make the necessary changes.

### CODE REVIEW

**Comment by 121hemank** [comment]
i want to work in your project

**Comment by jency1** [comment]
> i want to work in your project

@121hemank Sure, you can raise some issues and get the PR merged.

**Comment by ThunderShadows** [comment]
@121hemank Can you please merge my commit, it would be very helpful. Thank you.

**Review by multiverseweb — COMMENTED** [review]
Hey @ThunderShadows, In my opinion, the idea of the website is to provide information about the software in a `simple and accessible` way and these animations don't align with the stated idea. 
Also, there are many bugs in this PR, I have attached the screenshot below:
image

Thanks for your time and determination, but I don't think this typing effect is required.
Good luck!

**Pull request closed without merging**
