### PR TITLE
Changes made in website script.js

### PR DESCRIPTION
**Pull request by Deeptig9138**
Navbar Selector: Corrected to querySelector('.navbar').
Replaced this.scrollY: Changed all instances to window.scrollY.
Consolidated Event Listeners: Combined mouseenter and mouseleave listeners for the contribute button.
Error Handling: Added checks for data length in the addMarker function.
General Event Listener Optimization: Consolidated scroll event listeners.

### CODE REVIEW

**Comment by Deeptig9138** [comment]
done

**Review by multiverseweb — CHANGES_REQUESTED** [review]
Hey @Deeptig9138, I think something is wrong in the code...check it one. Refer to the screenshot below:
image

**Comment by Deeptig9138** [comment]
can you check once again? i am done resolving the issue

**Comment by jency1** [comment]
> can you check once again? i am done resolving the issue

@Deeptig9138 Your PR has some conflicting files. Resolve all conflicts.

**Comment by jency1** [comment]
> can you check once again? i am done resolving the issue

@Deeptig9138  Resolve all conflicts.

**Pull request closed without merging**
