### PR TITLE
UI Improvements Needed for Dataverse Website

### LINKED ISSUE #145: UI Improvements Needed for Dataverse Website
The current UI of the Dataverse website has a few noticeable issues that impact user experience and design clarity. Here's a summary of the key points:

**Website Name Not Visible:**

The branding or name of the website is not visible on the landing page, which diminishes the identity and recognition of the platform. It should be prominently displayed.

**Blank Screen on Scroll:**

When scrolling down the website, it turns into a black screen with no content or indicators, making it unclear whether there’s more information below or if the page has ended.

**Missing Seek Button:**

The website is missing a "seek" or navigation button that would help users quickly navigate to various sections or important features of the website. Adding a seek button would enhance usability, especially for first-time visitors.

**Suggestions for Improvement:**

_Enhance the Header:_ Ensure that the website name or logo is visible in the header or somewhere on the front view so that users can easily identify the platform.

_Content Below the Fold:_ Add meaningful content or visual cues when scrolling down so that the user is not faced with a blank screen.

_Add Seek Button:_ A seek or navigation button to jump between sections or back to the top could improve the navigation and user experience.

Please assign this issue to me.

**_Screenshot for Reference:_**

A screenshot highlighting the issues is attached.

Screenshot (225)

### PR DESCRIPTION
**Pull request by sanchitc05**
Fixes #145

### **Title: Add Draggable Scroll Bar for Desktop View**

**Description:**

This pull request introduces a draggable scroll bar feature to enhance the user experience for desktop and laptop users. The scroll bar appears on the right side of the webpage when viewed on larger screens, providing an alternative method for scrolling through the content. 

### **Key Features:**
- A fixed draggable scroll bar that appears only in desktop mode (hidden on screens smaller than 768px).
- The scroll handle allows users to scroll through the page by dragging it, making navigation smoother and more accessible for users who prefer not to use the mouse wheel or touchpad.
- The scroll bar has been styled to ensure it blends well with the website’s layout, offering a seamless user experience.

### **Changes Made:**
1. **HTML:**  
   - Added a `div` element for the scroll bar and handle to the `index.html` file.
   
2. **CSS:**  
   - Added styles to position the scroll bar on the right side of the screen, ensuring it remains visible and usable throughout the page.
   - Included media queries to hide the scroll bar on smaller screens to maintain a responsive layout.

3. **JavaScript:**  
   - Implemented JavaScript logic to allow the scroll bar handle to be draggable.
   - The page scrolls as the user drags the handle up or down, making the navigation intuitive.

### **Testing:**
- Tested on desktop view using different screen resolutions.
- Verified that the scroll bar is hidden on mobile devices and smaller screens.
- Confirmed smooth functionality for scrolling using the drag feature.

### **Why This Feature?**
- This draggable scroll bar improves the site's accessibility, particularly for users who may find scrolling with a mouse or touchpad inconvenient.
- It enhances the overall user experience by providing another means to navigate the website content.

### Type of change
- [ ] Bug fix
- [x] New feature

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

For your reference here's the screenshot of the changes I made.

WhatsApp Image 2024-10-22 at 9 34 01 AM

### CODE REVIEW

**Review by sanchitc05 — COMMENTED** [review]
Necessary changes are made.

**Comment by sanchitc05** [comment]
Hi @multiverseweb I have made the necessary changes, please check the PR and let me know if you want any modifications.

**Review by multiverseweb — CHANGES_REQUESTED** [review]
Hey @sanchitc05, what you were calling `seek button` is generally called `scroll bar`. It was hidden on-purpose using this simple piece of code:
image

This code is written [here](https://github.com/multiverseweb/Dataverse/blob/main/website/style.css#L198C1-L200C2).

The code you have implemented has following issues:
Screenshot 2024-10-22 094001

- Scroll bar overlapping with `scroll to top` button.
- Scroll bar going behind navbar.

Kindly resolve the issue by simple removing [these lines](https://github.com/multiverseweb/Dataverse/blob/main/website/style.css#L198C1-L200C2) from the current code in main repository.

**Comment by sanchitc05** [comment]
Okay @multiverseweb I'll resolve this issue.

**Pull request closed without merging**
